### ISSUE TITLE
Windows Python 2.7 build fails with no setup-python version

### ISSUE THREAD

**Issue by dirkf** [MatteoH2O1999/build-and-install-python#165]
In your PR #156 and [here](https://github.com/ytdl-org/build-and-install-python/actions/runs/5348905189/jobs/9699426332) a very nasty attempt to build Py2.7 for Windows is failing, and `actions/setup-python` has withdrawn 2.7.

Maybe no-one really wants this platform/Python combo but it goes against the ethos of your action.

Is it necessary to build these Pythons from source while MSI downloads are available? Eg https://www.python.org/ftp/python/2.7.18/python-2.7.18.amd64.msi

**Comment by MatteoH2O1999** [comment]
I am aware of this issue and I'm currently working on a solution. The removal of 2.7 by the actions guys took everyone by surprise and building on Windows is tricky.
Thanks for the suggestion of using msi downloads, and while that is something that I'll look into to speedup builds, I don't really want to introduce a hard-dependency on Python's ftp server: it could be unavailable for a number of reasons or they could decide to no longer offer that.
If you need support for Python 2.7 on Windows urgently, I would suggest temporarily downloading the installer and performing the installation directly in your workflow as a step or, if you prefer, feel free to fork this action and expand upon it for your specific needs.

**Comment by dirkf** [comment]
Just what I thought: forking is how I noticed. It's not urgent for me but the one failing combo does block release with the current workflow.

Separately, for information, the 2.6 build on Ubuntu 20.04 fails. Looks like it's doing some bootstrap thing where the `Makefile` runs a script with Py2 syntax (`print stuff` vs `print(stuff)`), but the script is being run by the system Python (3.8?). 

10000 grazie.

**Comment by MatteoH2O1999** [comment]
I'll close this as version [v1.4.0](https://github.com/MatteoH2O1999/build-and-install-python/releases/tag/v1.4.0) fixes this
